### ISSUE TITLE
Naming the script clearly for installing within kde plasma system settings "get new scripts"

### ISSUE THREAD

**Issue by Aqa-Ib** [nclarius/floating-tiles#3]
When installing the script from within kde plasma system settings "get new scripts", there is no easy clue about what version is the latest. Naming the script like "floating tiles v3.8" would solve the issue. I know you can finally understand which one is newer between "20211125162805" and "20211201143236" but it is so much easy to just read 3.8 and 3.7. Just my point of view :)

Thank you so much.

**Comment by Aqa-Ib** [comment]
In store.kde.org you can see the version 3.8 clearly in downloads section, but you can not see it whitin "get new scripts" from plasma system settings. That's the origin of the problem though, to be clear.
![Captura_2021-12-05_11h-48m-28s](https://user-images.githubusercontent.com/16420574/144743471-486a3261-5140-4f86-9bd5-b1cddd5608d0.png)

**Comment by nclarius** [comment]
Thanks for making me aware of that, I thought the version  numbers showed in the KWin settings as well. I can't rename the existing files but will do it for future releases.  

But aren't the extensions automatically updated through the package manager/Discover for you?

**Comment by Aqa-Ib** [comment]
Yes, indeed they upgrade automatically. It somehow upgraded the version 3.6 to the not-working version 3.7 instead of upgrading it to the latest 3.8. I don't know how did it happen because I don't know how/when does the system upgrade the kde store things. Maybe it upgraded it before 3.8 was published (I think it was but I don't know for sure). I have downgraded the version to 3.6 though, I will see if in the future it upgrades it again to 3.7 or 3.8. I will let you know.

Thank you so much.
