### ISSUE TITLE
Plasma crashes when closing some windows

### ISSUE THREAD

**Issue by linux-leo** [nclarius/floating-tiles#6]
If i open Librewolf for example (a firefox fork) and open the manage History View, Plasma crashes when I'm closing it again.

I'm using Wayland and KDE plasma 5.24.4

**Comment by nclarius** [comment]
I can't reproduce this on the same setup.

What makes you believe that the floating tiles script is causing the crash? Have you tried provoking the behavior while the script is disabled? Does it happen every time you close that window? You're saying "for example"; in which other cases exactly does this happen?

Do you get a "Plasma crashed" notification or are you observing some other behavior? Is it Plasma or KWin? If you got a crash notification, please attach the crash information.

**Comment by linux-leo** [comment]
I'm not getting a crash notification, I'm just stuck at a black screen with my mouse cursor.
It always happens, it also happened while I was using kmail, I will test that again too.
I open a tty to reboot my computer, is there anything else that i can do to get a crash log?

Here what I've found out:
Logging in with the script enabled crashes
Logging in without the script enabled and enabling it later doesn't crash
Logging in with the script enabled, disabling it and enabling it again crashes.

**Comment by linux-leo** [comment]
Using kmail it only happened twice and now I can't reproduce it (I opened a file manager on top of it and closed it), but on Librewolf it always happens.

It only happens when the script is trying to restore windows, disabling that feature fixes it for me, but i would still like to use it.

**Comment by linux-leo** [comment]
Maybe Wayland is whats crashing here, but I'm not sure

**Comment by nclarius** [comment]
Okay. First of all, please verify that you have the newest version of the script (v6.3) installed; find out with the info button in the KWin script system settings, and if it is not the newest version, update it via the "Get New Scripts ..." button and test whether the problem remains.

**Comment by nclarius** [comment]
If you are using the most recent version and the problem persists, the best way for me to figure out where it's going wrong if you're not getting a crash notification is to look at the log for the script.   

Unfortunately logging may require some detours to get working on Wayland. Could you please run the following in a terminal:
```
echo 'QT_LOGGING_RULES='js=true; kwin_scripting=true' >> ~/.bash_profile
kwriteconfig5 --file startkderc --group General --key systemdBoot true
kwriteconfig5 --file kwinrc --group Script-floatingtiles --key debugMode true
kwriteconfig5 --file kwinrc --group Script-floatingtiles --key fullDebugMode true
```
Then log out and in again, and tell me whether you are getting any output for
```
journalctl -g "floatingtiles:"
```
If the change is causing problems, you can revert it with
```
kwriteconfig5 --file startkderc --group General --key systemdBoot false
```

**Comment by linux-leo** [comment]
1. Yes, I do have Version 6.3 and installed it from the System Settings, not Discover.
2. Sorry, I'm not using systemd, but openrc. I don't have journalctl installed.

Should I try to reproduce this in a vm with systemd or set up logging in openrc? Even if I enable logging I don't know what the startkderc command does and would need some help setting it up with openrc.

**Comment by linux-leo** [comment]
Just confirmed that the issue isn't present on X11

**Comment by nclarius** [comment]
Hm okay, this is touching the limits of my knowledge. You can read more about Plasma systemd boot [here](https://invent.kde.org/plasma/plasma-workspace/-/wikis/Plasma-and-the-systemd-boot). I was told by KWin developer that it has nothing to do with the system boot and only affects how the Plasma session starts. But I don't know in what way it still interacts with systemd, and what if any the alternative for openrc is. If you're willing to do the work of setting it up in a VM, I think that would be easiest.

That it is a Wayland-only issue is also helpful to know.

**Comment by linux-leo** [comment]
I just tried it in a vm and didn't have this issue.

I think its specific to wayland + openrc, because it causes other things to break such as the plasma loading animation. (multiple distros have this issue)

Firefox also has the same Issue.

Should I try to enable logs for openrc anyway?

If Wayland is whats crashing then those plasma services set up with your commands wouldn't do anything anyway, but that also means there's no debug output. I think that's an issue Wayland need to fix.

**Comment by nclarius** [comment]
You can try to get the logs if you have an idea how to go about doing this (I unfortunately don't) and I'll see if it gives me anything obvious about what's going wrong, but if the glitch is specific to your openrc setup, I hope you can understand that I won't start working myself into a different init system in the hopes to be able to perform more extensive debugging.

**Comment by linux-leo** [comment]
I took a look at the logs, there weren't any errors, so its not something obvious and probably not easy to fix.

Sorry.

**Comment by nclarius** [comment]
Okay. Sorry I can't help any further.
